#include "i18n.h"

#include <map>
#include <mutex>

#include "embedded.h"   // generated by CMake: kLangEn, kLangDe, kLangRu, kLangUk, kChangelog, kChangelogDe, ...
#include "util.h"

#ifdef _WIN32
#include <windows.h>
#endif

// CHANGELOG.md in the active language (built in: en, de, ru, uk - other languages get the English one)
const char* EmbeddedChangelog() {
    const std::wstring code = i18n::Active();
    const unsigned char* p = code == L"de" ? kChangelogDe : code == L"ru" ? kChangelogRu : code == L"uk" ? kChangelogUk
                                                                                                         : kChangelog;
    return reinterpret_cast<const char*>(p);
}

namespace i18n {
namespace {

struct Lang {
    std::wstring code, name, aliases;   // from the [FILE] section
    const unsigned char* builtin = nullptr;
    std::vector<std::wstring> files;    // Langs/*.lng (override / extend the built-in texts)
};

std::mutex g_mu;
bool g_scanned = false;
std::vector<Lang> g_langs;
std::vector<std::wstring> g_hints;
std::wstring g_override, g_active, g_aimp;
std::map<std::string, std::wstring> g_en, g_cur;
bool g_loaded = false;

std::wstring Text(const unsigned char* p) { return util::DecodeText(reinterpret_cast<const char*>(p)); }

std::wstring FileText(const std::wstring& path) {
    std::string raw;
    return util::ReadFileBytes(path, raw, 1u << 20) ? util::DecodeText(raw) : std::wstring();
}

std::wstring Meta(const std::wstring& text, const wchar_t* key) {
    for (auto& kv : util::IniSection(text, L"FILE"))
        if (util::Lower(kv.first) == util::Lower(key)) return kv.second;
    return std::wstring();
}

Lang* Find(const std::wstring& code) {
    for (Lang& l : g_langs)
        if (util::Lower(l.code) == util::Lower(code)) return &l;
    return nullptr;
}

void Scan() {   // g_mu held
    if (g_scanned) return;
    g_scanned = true;
    const struct { const unsigned char* data; } builtin[] = {{kLangEn}, {kLangDe}, {kLangRu}, {kLangUk}};
    for (auto& b : builtin) {
        std::wstring t = Text(b.data);
        Lang l;
        l.code = Meta(t, L"Code");
        l.name = Meta(t, L"Name");
        l.aliases = Meta(t, L"Aliases");
        l.builtin = b.data;
        g_langs.push_back(l);
    }
    // Langs folder next to the plugin (the x64 build lives in a sub folder: look one level up too)
    std::wstring dir = util::ModuleDir();
    for (const std::wstring& base : {dir, util::DirName(dir)}) {
        std::wstring langs = base + util::kPathSep + L"Langs";
        for (const std::wstring& name : util::ListFiles(langs, L".lng")) {
            std::wstring path = langs + util::kPathSep + name;
            std::wstring t = FileText(path);
            std::wstring code = Meta(t, L"Code");
            if (code.empty()) code = util::Lower(util::FileNameNoExt(name));
            Lang* l = Find(code);
            if (!l) {
                g_langs.push_back(Lang());
                l = &g_langs.back();
                l->code = code;
                l->name = Meta(t, L"Name");
                l->aliases = Meta(t, L"Aliases") + L";" + util::FileNameNoExt(name);
                if (l->name.empty()) l->name = util::FileNameNoExt(name);
            }
            l->files.push_back(path);
        }
    }
}

void Parse(const std::wstring& text, std::map<std::string, std::wstring>& out) {
    for (auto& kv : util::IniSection(text, L"DiscordRPC"))
        out[util::ToUtf8(kv.first)] = util::ReplaceAll(kv.second, L"\\n", L"\n");
}

void LoadTable(const std::wstring& code, std::map<std::string, std::wstring>& out) {
    out.clear();
    if (Lang* l = Find(code)) {
        if (l->builtin) Parse(Text(l->builtin), out);
        for (const std::wstring& f : l->files) Parse(FileText(f), out);
    }
}

// Does one of AIMP's hints name this language? Codes ("ru") must match exactly, "(ru)" or "ru_RU"; words
// ("russian", "русский") may be part of the hint; numbers (LCID) must match exactly.
bool Matches(const Lang& l, const std::wstring& hintRaw) {
    std::wstring hint = util::Lower(util::Trim(hintRaw));
    if (hint.empty()) return false;
    for (std::wstring tok : util::Split(l.aliases + L";" + l.code + L";" + l.name, L';')) {
        tok = util::Lower(util::Trim(tok));
        if (tok.empty()) continue;
        bool digits = tok.find_first_not_of(L"0123456789") == std::wstring::npos;
        if (digits || tok.size() <= 3) {
            if (hint == tok || hint.find(L"(" + tok + L")") != std::wstring::npos || hint.rfind(tok + L"_", 0) == 0 ||
                hint.rfind(tok + L"-", 0) == 0)
                return true;
        } else if (hint.find(tok) != std::wstring::npos) {
            return true;
        }
    }
    return false;
}

std::wstring SystemLanguage() {
#ifdef _WIN32
    wchar_t name[LOCALE_NAME_MAX_LENGTH] = {0};
    if (GetUserDefaultLocaleName(name, LOCALE_NAME_MAX_LENGTH) > 0) return name;   // e.g. "ru-RU"
    return std::wstring();
#else
    for (const wchar_t* var : {L"LC_ALL", L"LC_MESSAGES", L"LANG"}) {
        std::wstring v = util::GetEnv(var);
        if (!v.empty() && v != L"C" && v != L"POSIX") return v;   // e.g. "ru_RU.UTF-8"
    }
    return std::wstring();
#endif
}

void Resolve() {   // g_mu held: pick the language and load its texts
    Scan();
    if (!g_loaded) {
        LoadTable(L"en", g_en);
        g_loaded = true;
    }
    std::wstring code;
    g_aimp.clear();
    for (const std::wstring& h : g_hints) {
        for (const Lang& l : g_langs)
            if (Matches(l, h)) { g_aimp = l.name; code = l.code; break; }
        if (!code.empty()) break;
    }
    if (code.empty()) {   // AIMP's language is unknown or has no translation: try the system language
        std::wstring sys = SystemLanguage();
        for (const Lang& l : g_langs)
            if (Matches(l, sys)) { code = l.code; break; }
    }
    if (!g_override.empty() && Find(g_override)) code = g_override;
    if (code.empty()) code = L"en";
    if (code == g_active) return;
    g_active = code;
    if (code == L"en") g_cur.clear();
    else LoadTable(code, g_cur);
    util::Log(L"Language: %ls (AIMP: %ls)", code.c_str(), g_aimp.empty() ? L"?" : g_aimp.c_str());
}

}  // namespace

void SetAimpHints(const std::vector<std::wstring>& hints) {
    std::lock_guard<std::mutex> lk(g_mu);
    g_hints = hints;
    Resolve();
}

void SetOverride(const std::wstring& code) {
    std::lock_guard<std::mutex> lk(g_mu);
    if (g_override == code && g_loaded) return;
    g_override = code;
    Resolve();
}

std::vector<Language> Available() {
    std::lock_guard<std::mutex> lk(g_mu);
    Scan();
    std::vector<Language> out;
    for (const Lang& l : g_langs) out.push_back({l.code, l.name.empty() ? l.code : l.name});
    return out;
}

std::wstring Active() {
    std::lock_guard<std::mutex> lk(g_mu);
    if (!g_loaded) Resolve();
    return g_active;
}

std::wstring AimpLanguage() {
    std::lock_guard<std::mutex> lk(g_mu);
    return g_aimp;
}

std::wstring T(const char* key) {
    std::lock_guard<std::mutex> lk(g_mu);
    if (!g_loaded) Resolve();
    auto it = g_cur.find(key);
    if (it != g_cur.end() && !it->second.empty()) return it->second;
    it = g_en.find(key);
    if (it != g_en.end()) return it->second;
    return util::FromUtf8(key);   // missing text: show the key (the tests check that this never happens)
}

}  // namespace i18n
